FROM node:14
WORKDIR /app
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
#ENV PATH /app/node_modules/.bin:$PATH
#RUN npm config set network-timeout 600000 -g
# If you are using a custom next.config.js file, uncomment this line.
# COPY --from=builder /app/next.config.js ./
RUN npm install
RUN npm build
ADD public /app/public
ADD  .next /app/.next
ADD  node_modules /app/node_modules
ADD  package.json /app/package.json

EXPOSE 3000
CMD ["npm", "start"]
